---
- name: Update Amazon Linux
  yum: 
    name: '*'
    state: latest
    update_only: yes
  become: yes
  tags:
    - linux

- name: Add extras repository
  shell: yum-config-manager --enable extras
  become: yes
  tags:
    - linux

- name: Install Yum Packages
  yum:
    name: 
      - "docker"
      - "jq"
      - "firewalld"
      - "httpd"
      - "python3"
      - "python3-pip"
      - "python3-setuptools"
    state: present
  tags:
    - linux

- name: Reboot machine
  reboot:
    test_command: 'whoami'
    msg: "Reboot initiated by Ansible"
    connect_timeout: 360