---
- name: Upgrade pip
  shell: python3 -m pip install --upgrade pip
  become: yes
  tags:
    - python

- name: Install pip packages
  shell: python3 -m pip install {{ item }}
  become: yes
  with_items: 
    - "docker"
    - "docker-compose"
  tags:
    - python