---
- name: Enable Docker service at startup
  service:
    name: docker
    state: started
    enabled: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tags:
    - docker

- name: Get info on docker host
  docker_host_info:
    images: yes
    verbose_output: yes
  register: result
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tags:
    - docker